### ISSUE TITLE
PID file permissions

### ISSUE THREAD

**Issue by waldanbridger** [jnrbsn/daemonocle#13]
Why not '644' [here](https://github.com/jnrbsn/daemonocle/blob/master/daemonocle/daemon.py#L118)? Default file mode for open() is '777' but that's not quite right.
So could you change it?
Just `self._pid_fd = os.open(self.pidfile, flags, mode=0o644)`

**Comment by jnrbsn** [comment]
I don't like the idea of hard coding it. The mode of the PID file can be controlled via the `umask` argument of `Daemon.__init__()`. The `umask` defaults to `0o22`.

**Comment by waldanbridger** [comment]
Oh, I see. Thanks. I think this issue can be closed.
