### ISSUE TITLE
pytest is hanging on debian build pkg

### ISSUE THREAD

**Issue by alvesadrian** [jnrbsn/daemonocle#14]
I: pybuild base:184: cd /tmp/b/python-daemonocle/.pybuild/pythonX.Y_2.7/build; python2.7 -m pytest tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.12rc1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /tmp/b/python-daemonocle, inifile: 
collected 25 items

tests/test_actions.py ..
tests/test_basics.py ...

**Comment by alvesadrian** [comment]
hello Jonathan, my name is Adrian, am a debian packager trying to push this project into debian python modules team, i'll need a little bit of your help because code builts out of the box but in debina with pytest is hanging

**Comment by alvesadrian** [comment]
am building this pkg for debian and am just wondering if your code is compatible with python3

**Comment by jnrbsn** [comment]
The tests do a bunch of weird things with processes and stuff. It could be all sorts of things causing it to hang.

Why are you trying to make a debian package out of this? People should be installing python packages via pip. I can't recommend any other way of installing it. You can do it if you want, but I'm not going to put much effort into making this work as a debian package. If you figure out the issue, feel free to submit a pull request.

**Comment by jnrbsn** [comment]
I'm closing this. Installing from PyPI via pip is the recommended way of installing this package. I don't recommend people install a Debian package, as it could easily get out-of-date.
