### ISSUE TITLE
How to let `do_action` return its result 'machine-readable' instead of writing it to `stdout`?

### ISSUE THREAD

**Issue by s-m-e** [jnrbsn/daemonocle#18]
Looking at the source code, it appears to me that one can not control the verbosity of `daemonocle` (?). For instance, I am trying to check the status of a daemon from a python script. So far, my only option seems to be parsing the output captured from a sub-process via stdout. I'd love to be able to just call `do_action`, turn off any verbosity to stdout through an optional parameter and let it return a dict with detailed information instead.

I'd be willing to submit a pull request if this feature is of any interest.

**Comment by s-m-e** [comment]
In case someone else needs this, too: [I implemented a small routine based on daemonocle's original code](https://gist.github.com/s-m-e/fdf244394cf7ca85d036d7d5fd99b6e2), which does exactly what I want: Tell me whether my daemon is up or down by returning either `True` or `False`. It assumes that one knows about the location of the pid file.

**Comment by jnrbsn** [comment]
In version 1.1.0, you can now get the status of a daemon as a `dict` by calling `daemon.get_status()`. You can also use the new `--json` CLI option for the `status` action.
