### ISSUE TITLE
core.py import error on Windows Systems

### ISSUE THREAD

**Issue by Karsten-Merkle** [jnrbsn/daemonocle#19]
though you catched the exception on calling resource functions,
you do a bare import of resource. But resource is not available on a Windows Pc...

Could you change
```python
  import resource
```
to
```python
  try:
    import resource
  except ImportError:
    None
```

**Comment by enf644** [comment]
I encountered the same problem.

**Comment by jnrbsn** [comment]
Sorry. Windows is not supported and never has been. This library is intended for Unix-like systems. I currently have no intention of supporting Windows.
