### ISSUE TITLE
Example fails: IndexError: list index out of range

### ISSUE THREAD

**Issue by guettli** [jnrbsn/daemonocle#26]
The example from the README fails:

```
user@host> python d.py

Traceback (most recent call last):
  File "d.py", line 16, in <module>
    daemon.do_action(sys.argv[1])
IndexError: list index out of range
```

**Comment by jnrbsn** [comment]
This is not a problem with the README. It's just a misunderstanding. `sys.argv[1]` means it's expecting a command-line argument. That's a standard Python thing.
