### ISSUE TITLE
Example fails for unclear reason

### ISSUE THREAD

**Issue by guettli** [jnrbsn/daemonocle#27]
Example fails for unclear reason::

```
user@host> python d.py start

Starting d.py ... FAILED
ERROR: Child exited immediately with exit code 1
```

I guess that's because I start the daemon as user, not as root.

But I don't like to guess. I better error message would be great.

**Comment by jnrbsn** [comment]
As stated elsewhere in the README, you can run your daemon in non-detached mode if you want to debug why it's not starting. Also, I highly recommend using the click integration.
