### ISSUE TITLE
Add support immediate exit (without warning)

### ISSUE THREAD

**Issue by guettli** [jnrbsn/daemonocle#29]
My daemon does terminate immediately if there is nothing to do.

Up to now this fails with the message "ERROR: Child exited immediately with exit code 0".

Is there a way to terminate immediately without creating an error message?

Maybe by doing `sys.exit(100)`?

**Comment by jnrbsn** [comment]
You can just check if there's work to do before trying to start the daemon. Daemons don't exit immediately.
