### ISSUE TITLE
Run binary inside daemonocle and intercept cli of that binary?

### ISSUE THREAD

**Issue by Viste** [jnrbsn/daemonocle#30]
Is it possible to run a binary inside daemonocle and intercept its cli in daemonocle.
This binary is a C program which normally runs inside screen, or tmux and is the only way to send it to background.
So can I wrap this binary in daemonocle and cli intercept it?

**Comment by jnrbsn** [comment]
There's an undocumented (but still well-tested) feature `daemonocle.helpers.ExecWorker` that lets you run any executable as a daemon. Have a look at this test for an example of how to use it:
https://github.com/jnrbsn/daemonocle/blob/v1.2.2/tests/test_helpers.py#L444

**Comment by Viste** [comment]
Thanks!
